services:
  frontend:
    hostname: frontend
    image: volimfit-frontend:latest
    container_name: volimfit-frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - NODE_OPTIONS=--max-old-space-size=768
    mem_limit: 1200m
    mem_reservation: 768m
    cpus: 0.80
    deploy:
      resources:
        limits:
          memory: 1200M
          cpus: "0.80"
        reservations:
          memory: 768M
          cpus: "0.40"
    volumes:
      - image_cache:/usr/app/.next/cache/images
volumes:
  image_cache:
