services:
  frontend:
    hostname: frontend
    image: volimfit-frontend:latest
    container_name: volimfit-frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
volumes:
      - image_cache:/usr/app/.next/cache/images
volumes:
  image_cache:
    

