services:
  frontend:
    hostname: frontend
    image: volimfit-frontend:latest
    container_name: volimfit-frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - NODE_OPTIONS=--max-old-space-size=384
    mem_limit: 700m
    mem_reservation: 512m
    cpus: 0.50
    deploy:
      resources:
        limits:
          memory: 700M
          cpus: "0.50"
        reservations:
          memory: 512M
          cpus: "0.25"
    volumes:
      - image_cache:/usr/app/.next/cache/images
volumes:
  image_cache:
